name: Examples

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: configure
      run:  |
        echo 'APT::Get::Assume-Yes "true";' | sudo tee /etc/apt/apt.conf.d/90ci >/dev/null
        sudo apt-get update
        sudo apt-get install unzip libsuitesparse-dev liblapacke-dev libunistring-dev fonts-freefont-ttf
        python -m pip install --upgrade pip
        python -m pip install regex colored
    - name: make
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        sudo make install
        sudo mkdir /usr/local/lib/morpho
    - name: getcli
      run: |
        git clone https://github.com/Morpho-lang/morpho-cli.git
        cd morpho-cli
        mkdir build
        cd build
        cmake ..
        sudo make install
    - name: morphopm
      run: |
        git clone https://github.com/Morpho-lang/morpho-morphopm.git
        sudo mkdir -p /usr/local/share/morphopm
        sudo cp -a morpho-morphopm/packages/. /usr/local/share/morphopm/
        sudo install -m 755 morpho-morphopm/morphopm /usr/local/bin/morphopm
        morphopm install morphoview povray optimize4
    - name: test
      run: |
        cd examples
        python3 examples.py -c
